#!/usr/bin/env python3
"""
Automated calibration script for LCA_5 steering control.

This script tests the relationship between commanded angles and actual
steering angle (from PSCM_ANGLE_SENSOR via carState.steeringAngleDeg).

Two modes:
  1. Raw mode (--raw): Test raw LCA_5_STEER values (1° resolution)
  2. Angle mode (default): Test apply_angle with 2-byte encoding (~0.056° resolution)

Usage:
  1. Start openpilot normally (car on, engaged or ready to engage)
  2. Run this script: python calibrate_angle_factor.py
  3. The script will automatically:
     - Iterate through test values
     - Wait for steering to settle (detected automatically)
     - Log observed angles
     - Report the results

Requirements:
  - openpilot must be running (carState must be published)
  - Car should be stationary or moving slowly
  - Steering must be free to move (not held by driver)

Output:
  - CSV log file: /data/openpilot/angle_factor_calibration.csv
  - Results printed to console
"""

import sys
import time
import signal
import argparse
import statistics
from pathlib import Path

# Add openpilot to path if needed
OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

# Configuration
LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/angle_factor_calibration.csv"

# Settling detection parameters
SETTLE_THRESHOLD_DEG = 0.1   # Angle must be stable within this range
SETTLE_WINDOW = 15           # Number of samples to check for stability
SETTLE_TIMEOUT_S = 5.0       # Max time to wait for settling
SAMPLE_INTERVAL_S = 0.05     # 50ms between samples (20Hz)

# Final sampling after settling
FINAL_SAMPLE_COUNT = 20      # Number of samples to average for final reading

# Safety limits
MAX_ANGLE_DEG = 40.0         # Stop if angle exceeds this

# Default test values for angle mode (degrees) - tests fine-grained control
DEFAULT_ANGLE_VALUES = [0, 0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 0, -0.5, -1.0, -1.5, -2.0, -3.0, -5.0, -10.0, 0]

# Default test values for raw mode (raw LCA_5_STEER values)
DEFAULT_RAW_VALUES = [0, 5, 10, 15, 20, 25, 30, 0, -5, -10, -15, -20, -25, -30, 0]


class AngleFactorCalibrator:
  def __init__(self, test_values: list[float], max_angle: float, raw_mode: bool = False):
    self.test_values = test_values
    self.max_angle = max_angle
    self.raw_mode = raw_mode
    self.results = []  # List of (commanded_value, avg_angle, std_angle) tuples
    self.running = True

    # Set up signal handler for graceful exit
    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted, cleaning up...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, value: float):
    """Write test configuration to live_testing.txt"""
    if self.raw_mode:
      # Raw mode: directly set LCA_5_STEER
      content = f"""# Auto-generated by calibrate_angle_factor.py (raw mode)
lat_active=True
lca_5.lca_5_steer={int(value)}
"""
    else:
      # Angle mode: set apply_angle (uses 2-byte encoding)
      content = f"""# Auto-generated by calibrate_angle_factor.py (angle mode)
lat_active=True
apply_angle={value}
"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write(content)

  def _disable_live_testing(self):
    """Disable live testing by setting lat_active=False"""
    content = """# Auto-generated by calibrate_angle_factor.py
lat_active=False
"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write(content)
    print("Live testing disabled")

  def _get_angle(self, sm) -> float | None:
    """Get current steering angle from carState"""
    sm.update(timeout=1000)
    if sm.updated['carState']:
      return sm['carState'].steeringAngleDeg
    return None

  def _wait_for_settle(self, sm) -> bool:
    """
    Wait until steering angle stabilizes.
    Returns True if settled, False if timeout or interrupted.
    """
    recent_angles = []
    start_time = time.time()

    while self.running:
      # Check timeout
      if time.time() - start_time > SETTLE_TIMEOUT_S:
        print(f"  WARNING: Settle timeout after {SETTLE_TIMEOUT_S}s")
        return False

      # Get current angle
      angle = self._get_angle(sm)
      if angle is None:
        continue

      recent_angles.append(angle)

      # Keep only the last SETTLE_WINDOW samples
      if len(recent_angles) > SETTLE_WINDOW:
        recent_angles.pop(0)

      # Check if settled (need full window)
      if len(recent_angles) >= SETTLE_WINDOW:
        angle_range = max(recent_angles) - min(recent_angles)
        if angle_range < SETTLE_THRESHOLD_DEG:
          elapsed = time.time() - start_time
          print(f"  Settled in {elapsed:.2f}s (range: {angle_range:.3f}°)")
          return True

      time.sleep(SAMPLE_INTERVAL_S)

    return False

  def _collect_samples(self, sm, count: int) -> list[float]:
    """Collect multiple steering angle samples after settling"""
    samples = []
    for _ in range(count):
      if not self.running:
        break
      angle = self._get_angle(sm)
      if angle is not None:
        samples.append(angle)
      time.sleep(SAMPLE_INTERVAL_S)
    return samples

  def run(self):
    """Run the calibration sequence"""
    print("Connecting to carState...")
    sm = messaging.SubMaster(['carState'])

    # Wait for valid data
    print("Waiting for carState messages...")
    for _ in range(50):  # 5 second timeout
      sm.update(timeout=100)
      if sm.updated['carState']:
        print(f"Connected! Initial steering angle: {sm['carState'].steeringAngleDeg:.2f}°")
        break
      time.sleep(0.1)
    else:
      print("ERROR: No carState messages received. Is openpilot running?")
      return

    # Open log file
    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,raw_value,angle_deg,sample_num\n")

      mode_str = "RAW (LCA_5_STEER only)" if self.raw_mode else "ANGLE (2-byte encoding)"
      print(f"\nStarting calibration with {len(self.test_values)} test points...")
      print(f"Mode: {mode_str}")
      print(f"Settle threshold: {SETTLE_THRESHOLD_DEG}°, Safety limit: ±{self.max_angle}°")
      print("-" * 60)

      for i, test_value in enumerate(self.test_values):
        if not self.running:
          break

        if self.raw_mode:
          print(f"\n[{i+1}/{len(self.test_values)}] Testing LCA_5_STEER = {int(test_value)}")
        else:
          print(f"\n[{i+1}/{len(self.test_values)}] Testing apply_angle = {test_value}°")

        # Write the test value
        self._write_live_testing(test_value)

        # Wait for steering to settle
        print(f"  Waiting for steering to settle...")
        if not self._wait_for_settle(sm):
          print(f"  Skipping this point (did not settle)")
          continue

        # Check safety limit
        current_angle = self._get_angle(sm)
        if current_angle is not None and abs(current_angle) > self.max_angle:
          print(f"  SAFETY: Angle {current_angle:.1f}° exceeds limit ±{self.max_angle}°, stopping!")
          break

        # Collect final samples
        print(f"  Collecting {FINAL_SAMPLE_COUNT} samples...")
        samples = self._collect_samples(sm, FINAL_SAMPLE_COUNT)

        if len(samples) < 3:
          print(f"  WARNING: Only got {len(samples)} samples, skipping this point")
          continue

        # Calculate statistics
        avg_angle = statistics.mean(samples)
        std_angle = statistics.stdev(samples) if len(samples) > 1 else 0

        # Log all samples
        timestamp = time.time()
        for j, angle in enumerate(samples):
          log.write(f"{timestamp},{test_value},{angle:.4f},{j}\n")
        log.flush()

        # Store result
        self.results.append((test_value, avg_angle, std_angle))
        print(f"  Result: {avg_angle:.3f}° (±{std_angle:.3f}°)")

    # Return to 0 before disabling
    print("\nReturning to center (0)...")
    self._write_live_testing(0)
    self._wait_for_settle(sm)

    # Disable live testing
    self._disable_live_testing()

    # Analyze results
    self._analyze_results()

  def _analyze_results(self):
    """Analyze collected data and compute angle_factor"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data points to compute factor")
      return

    print("\n" + "=" * 60)
    print("CALIBRATION RESULTS")
    print("=" * 60)

    mode_str = "RAW MODE (LCA_5_STEER only)" if self.raw_mode else "ANGLE MODE (2-byte encoding)"
    print(f"Mode: {mode_str}")

    # Print all data points
    col1_header = "Raw Value" if self.raw_mode else "Cmd Angle"
    print(f"\nData:")
    print(f"{col1_header:>12} {'Obs Angle':>14} {'Std Dev':>10} {'Error':>10}")
    print("-" * 50)
    for cmd_val, avg_angle, std_angle in self.results:
      error = avg_angle - cmd_val if not self.raw_mode else "N/A"
      if self.raw_mode:
        print(f"{int(cmd_val):>12} {avg_angle:>14.3f} {std_angle:>10.3f}")
      else:
        print(f"{cmd_val:>12.2f} {avg_angle:>14.3f} {std_angle:>10.3f} {error:>10.3f}")

    # Compute linear regression: observed = slope * commanded + intercept
    cmd_values = [r[0] for r in self.results]
    obs_angles = [r[1] for r in self.results]

    cmd_mean = statistics.mean(cmd_values)
    obs_mean = statistics.mean(obs_angles)

    numerator = sum((c - cmd_mean) * (o - obs_mean) for c, o in zip(cmd_values, obs_angles))
    denominator = sum((c - cmd_mean) ** 2 for c in cmd_values)

    if abs(denominator) < 1e-10:
      print("\nERROR: Cannot compute regression (no variation in commanded values)")
      return

    slope = numerator / denominator
    intercept = obs_mean - slope * cmd_mean

    if self.raw_mode:
      # Raw mode: compute angle_factor
      if abs(slope) < 1e-10:
        print("\nERROR: Cannot compute factor (slope too small)")
        return

      angle_factor = 1.0 / slope

      print(f"\n{'Linear Fit Results':^50}")
      print("-" * 50)
      print(f"  Slope (deg per raw unit): {slope:.6f}")
      print(f"  Intercept:                {intercept:.3f}°")

      print(f"\n{'COMPUTED ANGLE_FACTOR':^50}")
      print("=" * 50)
      print(f"\n  angle_factor = {angle_factor:.5f}\n")

    else:
      # Angle mode: check how well 2-byte encoding works
      # Ideal: slope = 1.0, intercept = 0.0
      errors = [obs - cmd for cmd, obs in zip(cmd_values, obs_angles)]
      mean_error = statistics.mean(errors)
      max_error = max(abs(e) for e in errors)
      rmse = (sum(e**2 for e in errors) / len(errors)) ** 0.5

      print(f"\n{'2-Byte Encoding Accuracy':^50}")
      print("=" * 50)
      print(f"  Slope (ideal=1.0):     {slope:.6f}")
      print(f"  Intercept (ideal=0):   {intercept:.3f}°")
      print(f"  Mean error:            {mean_error:.3f}°")
      print(f"  Max error:             {max_error:.3f}°")
      print(f"  RMSE:                  {rmse:.3f}°")

      if max_error < 0.2:
        print(f"\n  ✓ EXCELLENT: Fine-grained control is working!")
        print(f"    Resolution appears to be ~{0.05596:.3f}° per count")
      elif max_error < 0.5:
        print(f"\n  ✓ GOOD: 2-byte encoding is working with minor errors")
      elif max_error < 1.0:
        print(f"\n  ~ OK: 2-byte encoding has some errors")
      else:
        print(f"\n  ✗ POOR: 2-byte encoding may not be working as expected")

    # Warn if intercept is significant
    if abs(intercept) > 1.0:
      print(f"\n  WARNING: Intercept is {intercept:.2f}° (not zero)")
      print("  There may be an offset in the steering.")

    print(f"\nFull log saved to: {LOG_FILE}")


def main():
  parser = argparse.ArgumentParser(description='Calibrate LCA_5 steering control')
  parser.add_argument('--max-angle', type=float, default=MAX_ANGLE_DEG,
                      help=f'Safety limit - stop if angle exceeds this (default: {MAX_ANGLE_DEG}°)')
  parser.add_argument('--values', type=str, default=None,
                      help='Comma-separated list of values to test')
  parser.add_argument('--raw', action='store_true',
                      help='Raw mode: test LCA_5_STEER values directly (1° resolution)')
  parser.add_argument('--quick', action='store_true',
                      help='Quick mode: fewer test points')
  args = parser.parse_args()

  if args.values:
    test_values = [float(v.strip()) for v in args.values.split(',')]
  elif args.quick:
    if args.raw:
      test_values = [0, 10, 20, 0, -10, -20, 0]
    else:
      test_values = [0, 1.0, 2.0, 5.0, 0, -1.0, -2.0, -5.0, 0]
  else:
    test_values = DEFAULT_RAW_VALUES if args.raw else DEFAULT_ANGLE_VALUES

  mode_str = "RAW (LCA_5_STEER only, 1° resolution)" if args.raw else "ANGLE (2-byte encoding, ~0.056° resolution)"

  print("=" * 60)
  print("LCA_5 Steering Calibration")
  print("=" * 60)
  print(f"Mode: {mode_str}")
  print(f"Test values: {test_values}")
  print(f"Safety limit: ±{args.max_angle}°")
  print()
  print("IMPORTANT: Make sure:")
  print("  1. openpilot is running")
  print("  2. Car is stationary or moving slowly")
  print("  3. Don't touch the steering wheel during calibration")
  print()
  input("Press Enter to start calibration...")

  calibrator = AngleFactorCalibrator(test_values, args.max_angle, raw_mode=args.raw)
  calibrator.run()


if __name__ == "__main__":
  main()
