#!/usr/bin/env python3
"""
Calibration script to discover the relationship between LCA_5 signals and steering angle.

This script tests various combinations of LCA_TURN_BITS and LCA_5_STEER to
empirically determine how they affect the actual steering angle.

Modes:
  1. discover (default): Test combinations of both bytes to map the 2D relationship
  2. single: Test LCA_5_STEER only (with stock LCA_TURN_BITS)

Usage:
  python calibrate_angle_factor.py              # Discovery mode
  python calibrate_angle_factor.py --single     # Single byte mode

Requirements:
  - openpilot must be running (carState must be published)
  - Car should be stationary or moving slowly
  - Steering must be free to move (not held by driver)
"""

import sys
import time
import signal
import argparse
import statistics
from pathlib import Path

# Add openpilot to path if needed
OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

# Configuration
LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/angle_calibration.csv"

# Settling detection parameters
SETTLE_THRESHOLD_DEG = 0.15  # Angle must be stable within this range
SETTLE_WINDOW = 15           # Number of samples to check for stability
SETTLE_TIMEOUT_S = 5.0       # Max time to wait for settling
SAMPLE_INTERVAL_S = 0.05     # 50ms between samples (20Hz)

# Final sampling after settling
FINAL_SAMPLE_COUNT = 20      # Number of samples to average for final reading

# Safety limits
MAX_ANGLE_DEG = 40.0         # Stop if angle exceeds this


class SteeringCalibrator:
  def __init__(self, max_angle: float):
    self.max_angle = max_angle
    self.results = []  # List of (turn_bits, steer, avg_angle, std_angle) tuples
    self.running = True
    self.sm = None

    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted, cleaning up...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, turn_bits: int | None, steer: int | None):
    """Write test configuration to live_testing.txt"""
    lines = ["# Auto-generated by calibrate_angle_factor.py", "lat_active=True"]
    if turn_bits is not None:
      lines.append(f"lca_5.lca_turn_bits={turn_bits}")
    if steer is not None:
      lines.append(f"lca_5.lca_5_steer={steer}")

    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write('\n'.join(lines) + '\n')

  def _disable_live_testing(self):
    """Disable live testing"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write("# Auto-generated\nlat_active=False\n")
    print("Live testing disabled")

  def _get_angle(self) -> float | None:
    """Get current steering angle from carState"""
    self.sm.update(timeout=1000)
    if self.sm.updated['carState']:
      return self.sm['carState'].steeringAngleDeg
    return None

  def _wait_for_settle(self) -> bool:
    """Wait until steering angle stabilizes"""
    recent_angles = []
    start_time = time.time()

    while self.running:
      if time.time() - start_time > SETTLE_TIMEOUT_S:
        print(f"  WARNING: Settle timeout after {SETTLE_TIMEOUT_S}s")
        return False

      angle = self._get_angle()
      if angle is None:
        continue

      recent_angles.append(angle)
      if len(recent_angles) > SETTLE_WINDOW:
        recent_angles.pop(0)

      if len(recent_angles) >= SETTLE_WINDOW:
        angle_range = max(recent_angles) - min(recent_angles)
        if angle_range < SETTLE_THRESHOLD_DEG:
          elapsed = time.time() - start_time
          print(f"  Settled in {elapsed:.2f}s (range: {angle_range:.3f}°)")
          return True

      time.sleep(SAMPLE_INTERVAL_S)

    return False

  def _collect_samples(self, count: int) -> list[float]:
    """Collect steering angle samples"""
    samples = []
    for _ in range(count):
      if not self.running:
        break
      angle = self._get_angle()
      if angle is not None:
        samples.append(angle)
      time.sleep(SAMPLE_INTERVAL_S)
    return samples

  def _test_point(self, turn_bits: int | None, steer: int | None, log_file) -> tuple[float, float] | None:
    """Test a single (turn_bits, steer) combination"""
    tb_str = str(turn_bits) if turn_bits is not None else "stock"
    st_str = str(steer) if steer is not None else "stock"
    print(f"  Testing LCA_TURN_BITS={tb_str}, LCA_5_STEER={st_str}")

    self._write_live_testing(turn_bits, steer)

    print(f"    Waiting for settle...")
    if not self._wait_for_settle():
      return None

    # Safety check
    current_angle = self._get_angle()
    if current_angle is not None and abs(current_angle) > self.max_angle:
      print(f"    SAFETY: Angle {current_angle:.1f}° exceeds limit!")
      return None

    print(f"    Collecting samples...")
    samples = self._collect_samples(FINAL_SAMPLE_COUNT)

    if len(samples) < 3:
      print(f"    WARNING: Only {len(samples)} samples")
      return None

    avg_angle = statistics.mean(samples)
    std_angle = statistics.stdev(samples) if len(samples) > 1 else 0

    # Log to file
    timestamp = time.time()
    for i, angle in enumerate(samples):
      log_file.write(f"{timestamp},{turn_bits},{steer},{angle:.4f},{i}\n")
    log_file.flush()

    print(f"    Result: {avg_angle:.3f}° (±{std_angle:.3f}°)")
    return (avg_angle, std_angle)

  def connect(self) -> bool:
    """Connect to carState"""
    print("Connecting to carState...")
    self.sm = messaging.SubMaster(['carState'])

    print("Waiting for messages...")
    for _ in range(50):
      self.sm.update(timeout=100)
      if self.sm.updated['carState']:
        print(f"Connected! Initial angle: {self.sm['carState'].steeringAngleDeg:.2f}°")
        return True
      time.sleep(0.1)

    print("ERROR: No carState messages. Is openpilot running?")
    return False

  def run_single_mode(self):
    """Test LCA_5_STEER only (stock LCA_TURN_BITS)"""
    if not self.connect():
      return

    test_values = [0, 5, 10, 15, 20, 25, 30, 0, -5, -10, -15, -20, -25, -30, 0]

    print(f"\n{'='*60}")
    print("SINGLE BYTE MODE: Testing LCA_5_STEER with stock LCA_TURN_BITS")
    print(f"{'='*60}")
    print(f"Test values: {test_values}")
    print(f"Safety limit: ±{self.max_angle}°\n")

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,lca_turn_bits,lca_5_steer,angle_deg,sample_num\n")

      for i, steer in enumerate(test_values):
        if not self.running:
          break
        print(f"\n[{i+1}/{len(test_values)}]")
        result = self._test_point(None, steer, log)
        if result:
          self.results.append((None, steer, result[0], result[1]))

    # Return to neutral
    print("\nReturning to neutral...")
    self._write_live_testing(None, 0)
    self._wait_for_settle()
    self._disable_live_testing()

    self._analyze_single_mode()

  def run_discovery_mode(self):
    """Discover the relationship between both bytes"""
    if not self.connect():
      return

    # Test combinations to understand the 2D relationship
    # First, find what stock LCA_TURN_BITS is
    # Then test various combinations

    turn_bits_values = [186, 128, 255, 0, 64, 192]  # Common candidates
    steer_values = [0, 10, 20, -10, -20]  # Small range for safety

    print(f"\n{'='*60}")
    print("DISCOVERY MODE: Testing LCA_TURN_BITS + LCA_5_STEER combinations")
    print(f"{'='*60}")
    print(f"LCA_TURN_BITS values: {turn_bits_values}")
    print(f"LCA_5_STEER values: {steer_values}")
    print(f"Safety limit: ±{self.max_angle}°\n")

    total_tests = len(turn_bits_values) * len(steer_values)
    test_num = 0

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,lca_turn_bits,lca_5_steer,angle_deg,sample_num\n")

      for turn_bits in turn_bits_values:
        if not self.running:
          break
        print(f"\n{'='*40}")
        print(f"Testing LCA_TURN_BITS = {turn_bits}")
        print(f"{'='*40}")

        for steer in steer_values:
          if not self.running:
            break
          test_num += 1
          print(f"\n[{test_num}/{total_tests}]")
          result = self._test_point(turn_bits, steer, log)
          if result:
            self.results.append((turn_bits, steer, result[0], result[1]))

    # Return to neutral
    print("\nReturning to neutral...")
    self._write_live_testing(186, 0)  # Try inactive pattern
    self._wait_for_settle()
    self._disable_live_testing()

    self._analyze_discovery_mode()

  def _analyze_single_mode(self):
    """Analyze single byte mode results"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data")
      return

    print(f"\n{'='*60}")
    print("RESULTS: LCA_5_STEER → Steering Angle")
    print(f"{'='*60}")

    print(f"\n{'LCA_5_STEER':>12} {'Angle':>10} {'Std':>8}")
    print("-" * 35)
    for _, steer, angle, std in self.results:
      print(f"{steer:>12} {angle:>10.3f} {std:>8.3f}")

    # Linear regression
    steer_vals = [r[1] for r in self.results]
    angles = [r[2] for r in self.results]

    steer_mean = statistics.mean(steer_vals)
    angle_mean = statistics.mean(angles)

    num = sum((s - steer_mean) * (a - angle_mean) for s, a in zip(steer_vals, angles))
    den = sum((s - steer_mean) ** 2 for s in steer_vals)

    if abs(den) > 1e-10:
      slope = num / den
      intercept = angle_mean - slope * steer_mean
      print(f"\nLinear fit: angle = {slope:.4f} * LCA_5_STEER + {intercept:.3f}")
      print(f"(1 raw unit ≈ {slope:.3f}°)")

    print(f"\nLog saved to: {LOG_FILE}")

  def _analyze_discovery_mode(self):
    """Analyze discovery mode results"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data")
      return

    print(f"\n{'='*60}")
    print("RESULTS: (LCA_TURN_BITS, LCA_5_STEER) → Steering Angle")
    print(f"{'='*60}")

    # Group by turn_bits
    by_turn_bits = {}
    for turn_bits, steer, angle, std in self.results:
      if turn_bits not in by_turn_bits:
        by_turn_bits[turn_bits] = []
      by_turn_bits[turn_bits].append((steer, angle, std))

    for turn_bits in sorted(by_turn_bits.keys()):
      print(f"\nLCA_TURN_BITS = {turn_bits}:")
      print(f"  {'LCA_5_STEER':>12} {'Angle':>10} {'Std':>8}")
      print(f"  {'-'*32}")

      data = by_turn_bits[turn_bits]
      for steer, angle, std in sorted(data):
        print(f"  {steer:>12} {angle:>10.3f} {std:>8.3f}")

      # Compute slope for this turn_bits value
      if len(data) >= 2:
        steers = [d[0] for d in data]
        angles = [d[1] for d in data]
        s_mean = statistics.mean(steers)
        a_mean = statistics.mean(angles)
        num = sum((s - s_mean) * (a - a_mean) for s, a in zip(steers, angles))
        den = sum((s - s_mean) ** 2 for s in steers)
        if abs(den) > 1e-10:
          slope = num / den
          print(f"  Slope: {slope:.4f} deg/unit")

    print(f"\nLog saved to: {LOG_FILE}")


def main():
  parser = argparse.ArgumentParser(description='Discover LCA_5 steering signal relationship')
  parser.add_argument('--single', action='store_true',
                      help='Single byte mode: test LCA_5_STEER only')
  parser.add_argument('--max-angle', type=float, default=MAX_ANGLE_DEG,
                      help=f'Safety limit (default: {MAX_ANGLE_DEG}°)')
  args = parser.parse_args()

  print("=" * 60)
  print("LCA_5 Steering Signal Discovery")
  print("=" * 60)
  print()
  print("IMPORTANT:")
  print("  1. openpilot must be running")
  print("  2. Car should be stationary or moving slowly")
  print("  3. Don't touch the steering wheel")
  print()
  input("Press Enter to start...")

  calibrator = SteeringCalibrator(args.max_angle)

  if args.single:
    calibrator.run_single_mode()
  else:
    calibrator.run_discovery_mode()


if __name__ == "__main__":
  main()
