#!/usr/bin/env python3
"""
Automated calibration script for LCA_5_STEER angle_factor.

This script determines the relationship between LCA_5_STEER raw values
and actual steering angle (from SAS_ANGLE_SENSOR via carState.steeringAngleDeg).

Usage:
  1. Start openpilot normally (car on, engaged or ready to engage)
  2. Run this script: python calibrate_angle_factor.py
  3. The script will automatically:
     - Iterate through LCA_5_STEER raw values
     - Wait for steering to settle
     - Log observed angles
     - Compute and report the angle_factor

Requirements:
  - openpilot must be running (carState must be published)
  - Car should be stationary or moving slowly
  - Steering must be free to move (not held by driver)

Output:
  - CSV log file: /data/openpilot/angle_factor_calibration.csv
  - Computed angle_factor printed to console
"""

import os
import sys
import time
import signal
import argparse
import statistics
from pathlib import Path

# Add openpilot to path if needed
OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

# Configuration
LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/angle_factor_calibration.csv"
SETTLE_TIME_S = 1.5  # Time to wait for steering to settle after changing value
SAMPLE_COUNT = 20    # Number of angle samples to average per test point
SAMPLE_INTERVAL_S = 0.05  # 50ms between samples (20Hz)

# Test values for LCA_5_STEER (raw 8-bit values)
# Start from center, go left, back to center, go right
DEFAULT_TEST_VALUES = [128, 140, 160, 180, 200, 220, 240, 128, 116, 96, 76, 56, 36, 16, 128]


class AngleFactorCalibrator:
  def __init__(self, test_values: list[int], settle_time: float, sample_count: int):
    self.test_values = test_values
    self.settle_time = settle_time
    self.sample_count = sample_count
    self.results = []  # List of (raw_value, avg_angle, std_angle) tuples
    self.running = True

    # Set up signal handler for graceful exit
    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted, cleaning up...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, raw_value: int):
    """Write test configuration to live_testing.txt"""
    content = f"""# Auto-generated by calibrate_angle_factor.py
lat_active=True
lca_5.lca_5_steer={raw_value}
"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write(content)

  def _disable_live_testing(self):
    """Disable live testing by setting lat_active=False"""
    content = """# Auto-generated by calibrate_angle_factor.py
lat_active=False
"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write(content)
    print("Live testing disabled")

  def _sample_steering_angle(self, sm, count: int) -> list[float]:
    """Collect multiple steering angle samples"""
    samples = []
    for _ in range(count):
      if not self.running:
        break
      sm.update(timeout=1000)
      if sm.updated['carState']:
        samples.append(sm['carState'].steeringAngleDeg)
      time.sleep(SAMPLE_INTERVAL_S)
    return samples

  def run(self):
    """Run the calibration sequence"""
    print("Connecting to carState...")
    sm = messaging.SubMaster(['carState'])

    # Wait for valid data
    print("Waiting for carState messages...")
    for _ in range(50):  # 5 second timeout
      sm.update(timeout=100)
      if sm.updated['carState']:
        print(f"Connected! Initial steering angle: {sm['carState'].steeringAngleDeg:.2f}°")
        break
      time.sleep(0.1)
    else:
      print("ERROR: No carState messages received. Is openpilot running?")
      return

    # Open log file
    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,raw_value,angle_deg,sample_num\n")

      print(f"\nStarting calibration with {len(self.test_values)} test points...")
      print(f"Settle time: {self.settle_time}s, Samples per point: {self.sample_count}")
      print("-" * 60)

      for i, raw_value in enumerate(self.test_values):
        if not self.running:
          break

        print(f"\n[{i+1}/{len(self.test_values)}] Testing LCA_5_STEER = {raw_value}")

        # Write the test value
        self._write_live_testing(raw_value)

        # Wait for steering to settle
        print(f"  Waiting {self.settle_time}s for steering to settle...")
        time.sleep(self.settle_time)

        # Collect samples
        print(f"  Collecting {self.sample_count} samples...")
        samples = self._sample_steering_angle(sm, self.sample_count)

        if len(samples) < 3:
          print(f"  WARNING: Only got {len(samples)} samples, skipping this point")
          continue

        # Calculate statistics
        avg_angle = statistics.mean(samples)
        std_angle = statistics.stdev(samples) if len(samples) > 1 else 0

        # Log all samples
        timestamp = time.time()
        for j, angle in enumerate(samples):
          log.write(f"{timestamp},{raw_value},{angle:.4f},{j}\n")
        log.flush()

        # Store result
        self.results.append((raw_value, avg_angle, std_angle))
        print(f"  Result: {avg_angle:.3f}° (±{std_angle:.3f}°)")

    # Disable live testing
    self._disable_live_testing()

    # Analyze results
    self._analyze_results()

  def _analyze_results(self):
    """Analyze collected data and compute angle_factor"""
    if len(self.results) < 2:
      print("\nERROR: Not enough data points to compute factor")
      return

    print("\n" + "=" * 60)
    print("CALIBRATION RESULTS")
    print("=" * 60)

    # Print all data points
    print("\nRaw Data:")
    print(f"{'Raw Value':>12} {'Angle (deg)':>14} {'Std Dev':>10}")
    print("-" * 40)
    for raw_val, avg_angle, std_angle in self.results:
      print(f"{raw_val:>12} {avg_angle:>14.3f} {std_angle:>10.3f}")

    # Compute linear regression: angle = factor * (raw - offset)
    # Using least squares: factor = sum((x-x_mean)*(y-y_mean)) / sum((x-x_mean)^2)
    raw_values = [r[0] for r in self.results]
    angles = [r[1] for r in self.results]

    raw_mean = statistics.mean(raw_values)
    angle_mean = statistics.mean(angles)

    numerator = sum((r - raw_mean) * (a - angle_mean) for r, a in zip(raw_values, angles))
    denominator = sum((r - raw_mean) ** 2 for r in raw_values)

    if abs(denominator) < 1e-10:
      print("\nERROR: Cannot compute factor (no variation in raw values)")
      return

    # factor: degrees per raw unit
    degrees_per_raw = numerator / denominator
    offset = angle_mean - degrees_per_raw * raw_mean

    # The angle_factor we need is for: raw = angle_deg * angle_factor
    # So: angle_factor = 1 / degrees_per_raw
    if abs(degrees_per_raw) < 1e-10:
      print("\nERROR: Cannot compute factor (degrees_per_raw too small)")
      return

    angle_factor = 1.0 / degrees_per_raw

    print(f"\n{'Linear Fit Results':^40}")
    print("-" * 40)
    print(f"  Degrees per raw unit: {degrees_per_raw:.6f}")
    print(f"  Offset (raw=0):       {offset:.3f}°")
    print(f"  Center point (raw):   {-offset/degrees_per_raw:.1f}")

    print(f"\n{'COMPUTED ANGLE_FACTOR':^40}")
    print("=" * 40)
    print(f"\n  angle_factor = {angle_factor:.5f}\n")
    print("  Use this value in create_lca_5_message():")
    print(f"    angle_factor = {angle_factor:.5f}")
    print()

    # Compare with current value
    current_factor = 0.05596
    print(f"  Current value:  {current_factor}")
    print(f"  Computed value: {angle_factor:.5f}")
    print(f"  Difference:     {((angle_factor - current_factor) / current_factor * 100):.1f}%")

    print(f"\nFull log saved to: {LOG_FILE}")


def main():
  parser = argparse.ArgumentParser(description='Calibrate LCA_5_STEER angle_factor')
  parser.add_argument('--settle-time', type=float, default=SETTLE_TIME_S,
                      help=f'Seconds to wait for steering to settle (default: {SETTLE_TIME_S})')
  parser.add_argument('--samples', type=int, default=SAMPLE_COUNT,
                      help=f'Number of samples per test point (default: {SAMPLE_COUNT})')
  parser.add_argument('--values', type=str, default=None,
                      help='Comma-separated list of raw values to test (default: built-in sequence)')
  parser.add_argument('--quick', action='store_true',
                      help='Quick mode: fewer test points, shorter settle time')
  args = parser.parse_args()

  if args.values:
    test_values = [int(v.strip()) for v in args.values.split(',')]
  elif args.quick:
    test_values = [128, 180, 220, 128, 76, 36, 128]
    args.settle_time = 1.0
    args.samples = 10
  else:
    test_values = DEFAULT_TEST_VALUES

  print("=" * 60)
  print("LCA_5_STEER Angle Factor Calibration")
  print("=" * 60)
  print(f"Test values: {test_values}")
  print(f"Settle time: {args.settle_time}s")
  print(f"Samples per point: {args.samples}")
  print()
  print("IMPORTANT: Make sure:")
  print("  1. openpilot is running")
  print("  2. Car is stationary or moving slowly")
  print("  3. Don't touch the steering wheel during calibration")
  print()
  input("Press Enter to start calibration...")

  calibrator = AngleFactorCalibrator(test_values, args.settle_time, args.samples)
  calibrator.run()


if __name__ == "__main__":
  main()
